### ISSUE TITLE
package sxmo-svkbd

### ISSUE THREAD

**Issue by wentam** [wentam/sxmo-nix#26]
This is a fork of the stock svkbd that we have in nixpkgs that has a diff layout

**Comment by dotlambda** [comment]
I thought the fork was merged into upstream. That's why upstream svkbd gained traction again.

**Comment by wentam** [comment]
Maybe true. I'm just seeing that https://git.sr.ht/~mil/sxmo-svkbd/tree has layout.sxmo.h, 
while http://git.suckless.org/svkbd/files.html does not.

Edit: I suppose it's possible that layout.mobile-* is the same thing? sxmo-svkbd absolutely looks unmaintained.

**Comment by wentam** [comment]
![image](https://user-images.githubusercontent.com/901583/170827333-c00a1780-d9e2-4214-96eb-3d6c779075f9.png)
